package com.example.URLShortener.entity.enums;

public enum ErrorCode {
    UNEXPECTED_ERROR,
    NOT_IMPLEMENTED,

    METHOD_NOT_ALLOWED,
    ROLE_NOT_FOUND,
    URL_NOT_FOUND,
    URL_ALREADY_EXISTS,
    INVALID_URL_FORMAT,
    SHORT_CODE_TAKEN,
    KEY_POOL_EXHAUSTED,

    USER_NOT_FOUND,
    UNAUTHORIZED,
    FORBIDDEN,

    RATE_LIMIT_EXCEEDED,
    INVALID_PARAMETER_FORMAT,
    ROLE_ALREADY_EXISTS
}