spring.application.name=URLShortener

# Logging
logging.level.com.example.URLShortener=INFO
logging.level.com.example.URLShortener.logic=DEBUG
logging.level.org.springframework=WARN
logging.level.com.zaxxer.hikari=WARN
logging.file.name=logs/urlshortener.log
logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n%ex{full}

# Database
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Short code
short-code.prefix=u
short-code.minimum-length=6
short-code.maximum-length=16
short-code.body-length=5
short-code.case-sensitive=true
short-code.redirect-path=/r/

# Security
security.jwt.secret = 8f1570863147f5afc3df0999c35f6bedf1df6eef742eb589cf32d597ee4fcf80
security.jwt.issuer = nguyenphuchntt
security.jwt.access-token-expiration = 900000
security.jwt.refresh-token-expiration = 2592000000

# Pageable
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100