spring.application.name=URLShortener

# Database
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Short code
short-code.prefix=u
short-code.minimum-length=6
short-code.maximum-length=16
short-code.body-length=5
short-code.case-sensitive=true
short-code.redirect-path=/r/