import { useState } from 'react'
import { Copy, ExternalLink } from 'lucide-react'
import { Dialog } from '@/components/ui/Dialog'
import { Button } from '@/components/ui/Button'
import { Input } from '@/components/ui/Input'
import { useApi } from '@/app/providers'
import { useToast } from '@/components/feedback/ToastProvider'
import { copyToClipboard, toUserMessage } from '@/lib/utils'
import { validateLink } from '../validation'
import type { FieldErrors } from '@/features/auth/validation'
import type { ShortLink } from '../types'

export function CreateLinkDialog({ open, onClose, onCreated }: { open: boolean; onClose: () => void; onCreated: (link: ShortLink) => void }) {
  const { links } = useApi(); const { success, error } = useToast()
  const [values, setValues] = useState({ originalUrl: '', customCode: '', expiresAt: '' }); const [errors, setErrors] = useState<FieldErrors>({}); const [pending, setPending] = useState(false); const [created, setCreated] = useState<ShortLink | null>(null)
  const close = () => { if (!pending) { setCreated(null); setErrors({}); onClose() } }
  const update = (key: keyof typeof values, value: string) => { setValues((state) => ({ ...state, [key]: value })); setErrors((state) => ({ ...state, [key]: '' })) }
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const next = validateLink(values); setErrors(next); if (Object.keys(next).length) return; setPending(true); try { const link = await links.createLink({ originalUrl: values.originalUrl.trim(), customCode: values.customCode.trim() || undefined, expiresAt: values.expiresAt ? new Date(values.expiresAt).toISOString() : null }); setCreated(link); onCreated(link); setValues({ originalUrl: '', customCode: '', expiresAt: '' }); success('Link created successfully.') } catch (caught) { const apiError = caught as { fieldErrors?: FieldErrors }; setErrors(apiError.fieldErrors ?? {}); error(toUserMessage(caught, 'Could not create this link.')) } finally { setPending(false) } }
  const copy = async () => { if (!created) return; try { await copyToClipboard(created.shortUrl); success('Short URL copied.') } catch { error('Could not copy the short URL.') } }
  return <Dialog open={open} onClose={close} title={created ? 'Your link is ready' : 'Create a new link'} description={created ? 'Copy it now and share it anywhere.' : ''}>{created ? <div><div className="rounded-lg border border-blue-100 bg-blue-50 p-4"><p className="font-mono text-sm font-semibold text-signal">{created.shortUrl}</p><p className="mt-2 break-all text-xs text-muted">{created.originalUrl}</p></div><div className="mt-5 flex justify-end gap-3"><Button variant="secondary" onClick={close}>Done</Button><Button onClick={copy}><Copy className="h-4 w-4" />Copy link</Button></div></div> : <form onSubmit={submit} noValidate className="space-y-4"><label className="block text-sm font-medium text-ink">Destination URL<Input className="mt-1.5" placeholder="https://example.com/" value={values.originalUrl} onChange={(e) => update('originalUrl', e.target.value)} error={errors.originalUrl} />{errors.originalUrl && <span className="mt-1 block text-xs text-danger">{errors.originalUrl}</span>}</label><label className="block text-sm font-medium text-ink">Custom alias <span className="font-normal text-muted">(optional)</span><div className="mt-1.5 flex"><span className="flex min-h-11 items-center rounded-l-lg border border-r-0 border-line bg-slate-50 px-3 text-sm text-muted">localhost:8080/</span><Input className="rounded-l-none" placeholder="custom shortcode" value={values.customCode} onChange={(e) => update('customCode', e.target.value.toLowerCase())} error={errors.customCode} /></div>{errors.customCode && <span className="mt-1 block text-xs text-danger">{errors.customCode}</span>}</label><label className="block text-sm font-medium text-ink">Expiration <span className="font-normal text-muted">(optional)</span><Input className="mt-1.5" type="datetime-local" value={values.expiresAt} onChange={(e) => update('expiresAt', e.target.value)} error={errors.expiresAt} />{errors.expiresAt && <span className="mt-1 block text-xs text-danger">{errors.expiresAt}</span>}</label><div className="flex justify-end gap-3 pt-2"><Button variant="secondary" type="button" onClick={close}>Cancel</Button><Button type="submit" loading={pending}>{pending ? 'Creating link…' : <><ExternalLink className="h-4 w-4" />Create link</>}</Button></div></form>}</Dialog>
}